[package]
name = "next-build-test"
version = "0.1.0"
description = "TBD"
license = "MPL-2.0"
edition = "2021"
autobenches = false

[[bin]]
name = "next-build-test"
path = "src/main.rs"
bench = false

[lints]
workspace = true

[dependencies]
next-core = { workspace = true }
next-api = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true, features = ["full"] }
turbo-tasks-malloc = { workspace = true, default-features = false }
turbopack-binding = { workspace = true, features = [
  "__turbo_tasks",
  "__turbo_tasks_memory",
  "__turbo_tasks_env",
  "__turbo_tasks_fs",
  "__turbo_tasks_memory",
  "__turbopack",
  "__turbopack_nodejs",
  "__turbopack_core",
  "__turbopack_browser",
  "__turbopack_ecmascript",
  "__turbopack_ecmascript_runtime",
  "__turbopack_env",
  "__turbopack_node",
] }
turbo-tasks = { workspace = true }

[build-dependencies]
turbopack-binding = { workspace = true, features = ["__turbo_tasks_build"] }
